import { createHmac } from "crypto";
import path from "path";
import fs from "fs/promises";
import type { StorageProvider } from "./types";

/**
 * LOCAL STORAGE PROVIDER (Development Only)
 *
 * This mimics real presigned URL behavior using our own API endpoint.
 * Files are saved to `public/uploads/` and served as static assets.
 *
 * In production, this entire file is replaced by an R2/S3 provider that
 * generates real presigned URLs. The API routes that call StorageProvider
 * don't change at all — that's the power of the abstraction.
 *
 * SECURITY NOTE:
 * The "presigned URL" in dev mode uses HMAC signatures to prevent
 * unauthorized uploads. This mirrors how S3 presigned URLs work:
 * - The server signs (key + contentType + expiry) with a secret
 * - The client includes the signature when uploading
 * - The store endpoint verifies the signature before accepting the file
 */

const UPLOAD_SECRET =
  process.env.UPLOAD_SECRET || "dev-secret-do-not-use-in-production";

const PRESIGNED_URL_EXPIRY_SECONDS = 300; // 5 minutes

/**
 * Generate an HMAC signature for a presigned URL.
 * HMAC = Hash-based Message Authentication Code.
 * It proves the URL was generated by our server (who knows the secret)
 * and hasn't been tampered with (any change invalidates the signature).
 */
function generateSignature(
  key: string,
  contentType: string,
  expiresAt: number
): string {
  return createHmac("sha256", UPLOAD_SECRET)
    .update(`${key}:${contentType}:${expiresAt}`)
    .digest("hex");
}

/** Verify an HMAC signature. Returns true if valid. */
export function verifySignature(
  key: string,
  contentType: string,
  expiresAt: number,
  signature: string
): boolean {
  const expected = generateSignature(key, contentType, expiresAt);
  // Use timing-safe comparison to prevent timing attacks.
  // A regular === leaks information about which characters matched
  // based on how long the comparison takes.
  if (expected.length !== signature.length) return false;
  let mismatch = 0;
  for (let i = 0; i < expected.length; i++) {
    mismatch |= expected.charCodeAt(i) ^ signature.charCodeAt(i);
  }
  return mismatch === 0;
}

export class LocalStorageProvider implements StorageProvider {
  private baseUrl: string;

  constructor(baseUrl: string = "http://localhost:3000") {
    this.baseUrl = baseUrl;
  }

  async generatePresignedUrl(
    key: string,
    contentType: string,
    expiresInSeconds: number = PRESIGNED_URL_EXPIRY_SECONDS
  ): Promise<{ presignedUrl: string; publicUrl: string }> {
    const expiresAt = Date.now() + expiresInSeconds * 1000;
    const signature = generateSignature(key, contentType, expiresAt);

    // Build a URL that points to our own store endpoint.
    // In production, this would be an S3/R2 URL with AWS query parameters.
    const params = new URLSearchParams({
      key,
      contentType,
      expires: expiresAt.toString(),
      signature,
    });

    return {
      presignedUrl: `${this.baseUrl}/api/upload/store?${params.toString()}`,
      publicUrl: `/${key}`,
    };
  }

  async deleteFile(key: string): Promise<void> {
    const filePath = path.join(process.cwd(), "public", key);
    try {
      await fs.unlink(filePath);
    } catch (error) {
      // File might already be deleted — that's fine (idempotent delete)
      if ((error as NodeJS.ErrnoException).code !== "ENOENT") {
        throw error;
      }
    }
  }

  /**
   * Save a file to the local filesystem.
   * Called by the store API route after verifying the signature.
   */
  async saveFile(key: string, data: Buffer): Promise<void> {
    const filePath = path.join(process.cwd(), "public", key);
    await fs.mkdir(path.dirname(filePath), { recursive: true });
    await fs.writeFile(filePath, data);
  }
}

/** Singleton instance — avoids creating a new instance on every request */
let instance: LocalStorageProvider | null = null;

export function getLocalStorageProvider(): LocalStorageProvider {
  if (!instance) {
    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
    instance = new LocalStorageProvider(baseUrl);
  }
  return instance;
}
